title: Belise Kunda Teta # your name (or website title) here
logo: "/IMG_1638_resize.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Rising Senior at University of Wisconsin-Madison studying Data Science & Industrial Engineering Majors
  <br><br>
  I am passionate about data analytics and its applications in making well-informed decisions that fuel global impact.
  <br><br>
  <a href="https://www.linkedin.com/in/belise-kunda-teta-0335b5132/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
