title: Belise Kunda Teta # your name (or website title) here
logo: "/IMG_1638.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Rising Senior at University of Wisconsin-Madison
  <br><br>
  Data Science & Industrial Engineering Majors
  <br><br>
  <a href="https://www.linkedin.com/in/belise-kunda-teta-0335b5132/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
